import heroImage1 from "./heroImage1.png";
import productImage1 from "./productImage1.png";
import shopifyImage from "./shopify.png";
import etsyImage from "./etsy.png";
import wixImage from "./wix.png";
import wooImage from "./woo.png";
import squareSpaceImage from "./squarespace.png";
import networkImage from "./network.png";
import printfulLogo from "./Printful.png";
import tree from "./tree.png";
import birdImage from "./bird.png";
export const HeroImage1 = heroImage1;
export const ProductImage1 = productImage1;
export const ShopifyImage = shopifyImage;
export const EtsyImage = etsyImage;
export const WixImage = wixImage;
export const WooImage = wooImage;
export const SquareSpaceImage = squareSpaceImage;
export const BirdImage = birdImage;
export const NetworkImage = networkImage;
export const PrintfulLogo = printfulLogo;
export const Tree = tree;
